spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show_sql: true
  main:
    allow-bean-definition-overriding: true